- name: Install Clamav
  apt: name={{ item }} state=latest install_recommends=no
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
  tags: install

- name: Install unofficial-sigs
  apt: name=clamav-unofficial-sigs state=latest install_recommends=no
  when: clamav_unofficial_sigs_enable
  tags: install

- name: clamav create log directory
  file: path=/var/log/clamav state=directory force=yes mode=0755 owner=clamav group=clamav
  tags: config
  
- name: clamav create run directory
  file: path=/var/run/clamav state=directory force=yes mode=0755 owner=clamav group=clamav
  tags: config
      
- name: clamav clamd config
  template: src=templates/clamd.conf.j2 dest=/etc/clamav/clamd.conf backup=yes
  tags: config
      
- name: clamav freshclam config
  template: src=templates/freshclam.conf.j2 dest=/etc/clamav/freshclam.conf backup=yes
  tags: config

- name: clamav clamav-unofficial-sigs config
  template: src=templates/clamav-unofficial-sigs.conf.j2 dest=/etc/clamav-unofficial-sigs.conf backup=yes
  when: clamav_unofficial_sigs_enable
  tags: config
        
- name: clamav load sigs
  shell: |
    echo "Update clamav sigs"
    freshclam -c 1
    #echo "Update clamav unofficial-sigs"
    #if [ ! -e /var/lib/clamav/jurlbl.ndb ]; then
    #  /usr/sbin/clamav-unofficial-sigs
    #fi
    chown clamav.clamav -R /var/lib/clamav
  when: ansible_virtualization_type != "docker"
  tags: config
  
- name: clamav-daemon is running and service enabled
  service: name=clamav-daemon state=restarted enabled=yes
  when: not supervisor_enable and ansible_virtualization_type != "docker"
  tags: service
    
- name: docker clamav-daemon is not running and service disabled
  service: name=clamav-daemon state=stopped enabled=no
  when: supervisor_enable or ansible_virtualization_type == "docker"
  tags: service
    
- name: clamav-freshclam is running and service enabled
  service: name=clamav-freshclam state=restarted enabled=yes
  when: not supervisor_enable and ansible_virtualization_type != "docker"
  tags: service
    
- name: docker clamav-freshclam is not running and service disabled
  service: name=clamav-freshclam state=stopped enabled=no
  when: supervisor_enable or ansible_virtualization_type == "docker"
  tags: service

