---

- hosts: all
  gather_facts: yes
  #remote_user: ubuntu
  #--extra-vars "remote_user=root"
  remote_user: '{{ remote_user|default("ubuntu") }}'
  become: yes
  roles:
    - commons
  pre_tasks:
    - raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: '{{ hosts|default("radicalspam") }}'
  gather_facts: no
  #remote_user: ubuntu
  remote_user: '{{ remote_user|default("ubuntu") }}'
  become: yes
  roles:
    - syslog
    - postfix
    - postgrey
    - clamav
    - spamassassin
    - amavis
    - fail2ban
    - scripts
  