---

- hosts: all
  gather_facts: no
  remote_user: '{{ remote_user|default("ubuntu") }}'
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: all
  gather_facts: yes
  #remote_user: ubuntu
  #--extra-vars "remote_user=root"
  remote_user: '{{ remote_user|default("ubuntu") }}'
  become: yes
  roles:
    - commons

- hosts: '{{ hosts|default("radicalspam") }}'
  gather_facts: no
  #remote_user: ubuntu
  remote_user: '{{ remote_user|default("ubuntu") }}'
  become: yes
  vars:
    pdns_rec_config:
      'allow-from': '127.0.0.1/8'
      'local-address': 127.0.0.1
      #'server-id': 'nothing to see here'  
  roles:
    - syslog
    - { role: pdns, when: pdns_enable }
    - { role: pdns_recursor-ansible, when: pdns_enable}
    - fail2ban
    - postfix
    - clamav
    - spamassassin
    - { role: postgrey, when: postgrey_enable }
    - { role: amavis, when: amavis_enable }
    - { role: docker, when: ansible_virtualization_type == "docker" }
    - { role: supervisor, when: supervisor_enable }
  