---

- hosts: all
  gather_facts: no
  remote_user: '{{ rs_remote_user|default("ubuntu") }}'
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: all
  strategy: debug
  gather_facts: yes
  #remote_user: ubuntu
  #--extra-vars "remote_user=root"
  remote_user: '{{ rs_remote_user|default("ubuntu") }}'
  become: yes
  roles:
    - commons

- hosts: '{{ rs_hosts|default("radicalspam") }}'
  strategy: debug
  gather_facts: no
  #remote_user: ubuntu
  remote_user: '{{ rs_remote_user|default("ubuntu") }}'
  become: yes
  vars:
    pdns_rec_config:
      'allow-from': '127.0.0.1/8'
      'local-address': 127.0.0.1
      #'server-id': 'nothing to see here'  
  roles:
    - { role: syslog, when: syslog_enable }
    - { role: pdns, when: pdns_enable }
    - { role: pdns_recursor-ansible, when: pdns_enable}
    - { role: fail2ban, when: fail2ban_enable }
    - { role: postfix, when: postfix_enable }
    - { role: clamav, when: clamav_enable }
    - { role: spamassassin, when: sa_enable }
    - { role: postgrey, when: postgrey_enable }
    - { role: amavis, when: amavis_enable }
    - { role: docker, when: ansible_virtualization_type == "docker" }
    - { role: supervisor, when: supervisor_enable }
  