- name: put hostname to /etc/mailname
  copy: content="{{hostname_fqdn}}" dest=/etc/mailname backup=no

- name: install postfix
  apt: name=postfix state=latest install_recommends=no
  tags: install

- name: postfix create local directory
  file: path=/etc/postfix/local state=directory force=yes mode=0755
  tags: config

- name: postfix copy empty files
  copy: src=local/ dest=/etc/postfix/local
  
- name: postfix config - aliases
  template: src=templates/aliases.j2 dest=/etc/aliases
  tags: config

- name: postfix config locals > directory
  template: src=templates/directory.j2 dest=/etc/postfix/local/directory
  tags: config

- name: postfix config locals > relays
  template: src=templates/relays.j2 dest=/etc/postfix/local/relays
  tags: config

- name: postfix config locals > spoofing
  template: src=templates/spoofing.j2 dest=/etc/postfix/local/spoofing
  tags: config

- name: postfix config locals > transport
  template: src=templates/transport.j2 dest=/etc/postfix/local/transport
  tags: config

- name: postfix config locals > verify-recipients
  template: src=templates/verify-recipients.j2 dest=/etc/postfix/local/verify-recipients
  tags: config

- name: postfix config main
  template: src=templates/main.cf.j2 dest=/etc/postfix/main.cf backup=yes
  tags: config

- name: postfix config master
  template: src=templates/master.cf.j2 dest=/etc/postfix/master.cf backup=yes
  tags: config

- name: postfix config script
  template: src=templates/postfix-config.sh.j2 dest=/etc/postfix/local/postfix-config.sh mode=0750 backup=yes
  tags: config

- name: postfix finished config
  shell: /etc/postfix/local/postfix-config.sh
  when: ansible_virtualization_type != "docker"
  tags: config
  
- name: postfix is running and service enabled
  service: name=postfix state=restarted enabled=yes
  when: not supervisor_enable and ansible_virtualization_type != "docker"
  tags: service
    
- name: docker postfix is not running and service disabled
  service: name=postfix state=stopped enabled=no
  when: ansible_virtualization_type == "docker"
  tags: service

    