---

- name: Set local timezone
  timezone: name={{timezone}}
  notify: update tzdata
  
- name: set hostname
  hostname: name="{{hostname_fqdn}}"
  
- name: put hostname to /etc/hosts
  copy: content="127.0.1.1 {{hostname_fqdn}} localhost" dest=/etc/hosts backup=no

- name: apt-get update
  apt: update_cache=yes
  
- name: Install required
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - ca-certificates
    - curl
    - wget

- name: configure ovh failover interface
  template: src=templates/ovh-failover-interface.j2 dest=/etc/network/interfaces.d/ens3:0.cfg force=yes backup=yes
  when: failover_address is defined
  notify:
     - restart network
     - up failover interface  

  