- name: supervisor install
  apt: name=supervisor state=latest install_recommends=no
  tags: install

- name: supervisor config
  template: src=templates/supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf backup=yes
  tags: config

- name: copy postfix script
  copy: src=postfix.sh dest=/usr/local/bin/postfix-start mode=0755

- name: copy supervisor script
  copy: src=supervisor.sh dest=/usr/local/bin/supervisor-start mode=0755
  
- name: supervisor start services script
  template: src=templates/start-services.sh.j2 dest=/usr/local/bin/start-services backup=yes mode=0755
  tags: config
  
- name: supervisor is running and service enable
  service: name=supervisor state=started enabled=no
  when: supervisor_enable and ansible_virtualization_type != "docker"
  tags: service

- name: supervisor is not running and service disabled
  service: name=supervisor state=stopped enabled=no
  when: not supervisor_enable
  tags: service
    
- name: restart server
  command: /sbin/shutdown -r now
  when: ansible_virtualization_type != "docker"
  tags: command
