---

amavis_enable: true

amavis_bypass_abuse: true

#smtp:[127.0.0.1]:10025 or local:banned/%i-%n.gz
amavis_quarantine_method: smtp:[127.0.0.1]:10025
amavis_quarantine_to: "{{root_email}}" 

amavis_archive_enable: false

#D_BOUNCE | D_PASS | D_DISCARD | D_REJECT ?
amavis_destiny_unchecked: D_BOUNCE

amavis_max_servers: "{{postfix_filter_max_servers|default(2)}}"

amavis_spam_subject_tag2_maps: "[*** ? SPAM ***] " 
amavis_spam_subject_tag3_maps: "[*** SPAM ***] " 
 

#Spam?
amavis_sa_tag2_level_deflt: 8.0
#Spam confirmed:
amavis_sa_tag3_level_deflt: 10.0

amavis_redis_enable: false
amavis_redis_server: 

amavis_output_enable: false
amavis_output_forward_method: smtp:[127.0.0.1]:10025

amavis_sa_mail_body_size_limit: '400*1024'

amavis_banned_files: 
  - ade
  - adp
  - app
  - bas
  - bat
  - chm
  - cmd
  - com
  - cpl
  - crt
  - fxp
  - hlp
  - hta
  - inf
  - ins
  - isp
  - lnk
  - mdt
  - mdw
  - msc
  - msp
  - mst
  - ops
  - pif
  - prg
  - reg
  - scr
  - sct
  - shb
  - shs
  - vbs
  - wsc
  - wsf
  - wsh
