#OVH VPS cloud only
#failover_address:  1.1.1.1
#failover_name: ens3:0

hostname_fqdn: mx-demo.radical-spam.com
hostname: mx-demo

domains: 
  - radical-spam.com
  
transports:
  radical-spam.com: relay:[178.32.109.159]:1025 #hub mailhog
  
mynetworks:
  - 127.0.0.0/8
  - 94.23.34.88/32 #hub
  - 90.127.182.25/32 #maison
  
root_email: root@radical-spam.com

fail2ban_ignoreip:
  - 94.23.34.88/32 #hub
  - 90.127.182.25/32 #maison

amavis_quarantine_method: smtp:[178.32.109.159]:1025
amavis_quarantine_to: quarantine@radical-spam.com 
amavis_destiny_unchecked: D_PASS
  
clamav_unofficial_sigs_enable: true  

postfix_certificate_country: FR
postfix_certificate_state: Paris
postfix_certificate_location: Paris
postfix_certificate_organisation: radical-spam.com
postfix_certificate_orgunit: S2LTIC
postfix_certificate_email: postmaster@radical-spam.com
postfix_certificate_days_valid: 3650
