global:
  nodes: 
    - yaml:///etc/rs/data.yml
    #- etc://127.0.0.1:4001
      
apps:
  clamav:
    clamd:
      keys:
         - /clamav/clamd
      src: clamav/clamd.tmpl
      dest: /etc/clamav/clamd.conf
      check_cmd: "sv check /etc/service/clamd"
      reload_cmd: "sv hup /etc/service/clamd"         

  postfix:
    master:
       src: postfix/master.tmpl
       dest: /etc/postfix/master.cf
       check_cmd: "sv check /etc/service/postfix"
       reload_cmd: "sv hup /etc/service/postfix"
       owner:
