---

fail2ban_enable: "{{ lookup('env','FAIL2BAN_ENABLE')|default(true) }}"

fail2ban_ignoreip:
  - 127.0.0.0/8
  
fail2ban_bantime: 604800

fail2ban_findtime: 7200

fail2ban_maxretry: 1

#yes, no, warn
fail2ban_usedns: warn
  
fail2ban_destemail: '{{root_email}}'